const C='snap-pop-2026-09-22-predeploy-b';
const A=["./","index.html","styles.css","app.js","snap-bridge.js","manifest.json","Snap_Pop_UI_MASTER_LOGIC_REV_12.md","SNAP_EXPLORATION_CREW_MASTER_2026-09-20.md","SNAP_EXPLORATION_CREW_SOURCE_LEDGER_2026-09-20.md","data/landmarks.json","data/growth.json","data/exploration-crew-rules.json","assets/world/golden_world_scene.jpg","assets/growth/stage_01.png","assets/growth/stage_02.png","assets/growth/stage_03.png","assets/growth/stage_04.png","assets/growth/stage_05.png","assets/growth/stage_06.png","assets/icons/map.svg","assets/icons/records.svg","assets/icons/explore.svg","assets/icons/gems.svg","assets/icons/growth.svg","assets/icons/radio.svg","assets/icons/gear.svg","assets/icons/speaker.svg","badge-catalog-guard-runtime.js","badge-candidate-runtime.js","badge-runtime.js","badge-evidence-contract-runtime.js","badge-behavior-runtime.js","badge-shared-contract-runtime.js","badge-theme-expression-runtime.js","badge-visual-runtime.js","learning-context-runtime.js","vocabulary-material-runtime.js","openai-semantic-provider.js","openai-expression-bridge-provider.js","expression-bridge-runtime.js","semantic-writing-runtime.js","writing-runtime.js","truth-guard-runtime.js","openai-knowledge-provider.js","knowledge-runtime.js","mental-model-runtime.js","curiosity-scaffold-runtime.js","authorship-guard-runtime.js","crew-interaction-safety-runtime.js","crew-intervention-runtime.js","crew-presentation-guard.js","crew-orchestration-runtime.js","crew-role-guard-runtime.js","crew-core6-runtime.js","imagination-return-runtime.js","intelligence-runtime.js","voice-runtime.js","family-expansion-runtime.js","app-storage-runtime.js","app-shell-runtime.js","writing-controller.js","crew-controller.js","crew-runtime-controller.js","records-growth-controller.js","records-flow-controller.js","wish-economy-controller.js","special-controller.js","imagination-controller.js","settings-profile-controller.js","badge-controller.js","bridge-context-controller.js","interaction-support-controller.js","bootstrap-controller.js","writing-flow-controller.js","family-expansion-app.js","scripts/browser-runtime-selftest.js","icons/icon-192.png","icons/icon-512.png"];
self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(x=>x.addAll(A)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==C).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET')return;
 const u=new URL(e.request.url);if(u.origin!==location.origin)return;
 if(e.request.mode==='navigate'){
   e.respondWith(fetch(e.request).then(r=>{const copy=r.clone();caches.open(C).then(c=>c.put('index.html',copy));return r}).catch(()=>caches.match('index.html')));return;
 }
 e.respondWith(fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();caches.open(C).then(c=>c.put(e.request,copy));}return r}).catch(()=>caches.match(e.request)));
});
