'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const records=fs.readFileSync(path.join(root,'snap-badge-records.js'),'utf8');
assert(index.includes('snap-badge-records.js'));
assert(index.includes('data-record-mode="journal"'));
assert(index.includes('data-record-mode="collection"'));
assert(index.includes('data-record-mode="calendar"'));
assert(index.includes('id="badgeCalendarGrid"'));
assert(index.includes('id="badgeDetailHistory"'));
assert(sw.includes("'snap-badge-records.js'"));
assert(sw.includes("u.pathname.startsWith('/api/')"));
assert(sw.includes("e.respondWith(fetch(e.request));return"));
assert(!records.includes("indexedDB.open("));
assert(!records.includes("localStorage.setItem("));
assert(!records.includes("appendApprovedDecision"));
assert(!records.includes("award_status:'AWARDED'"));
assert(!records.includes("get('gems')"));
assert(records.includes('TAKY_AUTHENTICATED_CHILD_BADGE_VIEWER_V1'));
assert(records.includes('TAKY_CHILD_BADGE_CALENDAR_V1'));
assert(records.includes('TAKY_CHILD_APPROVED_BADGE_COLLECTION_V1'));
assert(!app.includes("get('badge_awards')"));
console.log('SNAP_BADGE_RECORDS_SHELL_PASS: read-only authentic projection surface; no auto-award or private API cache');
