const assert=require('node:assert/strict');
globalThis.TakyExplorerCrewRelationRuntimeV1=require('../vendor/taky/explorer-crew-browser-relation-v1.js');
const e=require('../snap-crew-evidence-runtime-v1.js');
const map=new Map();const storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};
assert.equal(e.relationship(storage,'C1'),'NOT_MET');
assert.equal(e.behaviorRelationship(storage,'C1'),'FIRST_ENCOUNTER');
let first=e.append(storage,{event_id:'first',type:'FIRST_MEETING',verified:true,evidence_ref:'EV-FIRST',character_id:'C1',source:'SNAP_POP',at:'2026-09-30T12:00:00Z'});
assert.equal(first.ok,true);
assert.equal(e.relationship(storage,'C1'),'NOT_MET');
assert.equal(e.behaviorRelationship(storage,'C1'),'KNOWN');
let x=e.append(storage,{event_id:'1',type:'SHARED_EPISODE',verified:true,evidence_ref:'EV-1',character_id:'C1',source:'SNAP_POP',at:'2026-09-30T12:01:00Z'});
assert.equal(x.ok,true);
assert.equal(e.commitRelationship(storage,'C1','FAMILIAR',null).ok,false);
const noPolicy=e.relationCandidate(storage,'C1',null);assert.equal(noPolicy.reason,'APPROVED_RELATION_POLICY_REQUIRED');
const candidate=e.relationCandidate(storage,'C1',{approved:true,authority_ref:'POLICY:1',familiar_min_verified_episodes:1,trusted_min_verified_episodes:3});
assert.equal(candidate.ok,true);assert.equal(candidate.candidate_state,'FAMILIAR');assert.equal(candidate.promotion_auto_commit,false);
assert.equal(e.relationship(storage,'C1'),'NOT_MET');
assert.equal(e.commitRelationship(storage,'C1','FAMILIAR','TAKY_RELATION_COMMIT:1').ok,true);
assert.equal(e.relationship(storage,'C1'),'FAMILIAR');
assert.equal(e.behaviorRelationship(storage,'C1'),'FAMILIAR');
assert.equal(e.append(storage,{event_id:'1',type:'SHARED_EPISODE',verified:true,evidence_ref:'EV-1',character_id:'C1'}).reason,'DUPLICATE_EVENT');
assert.equal(e.append(storage,{type:'HELP_ACCEPTED',verified:false,evidence_ref:'EV-X',character_id:'C1'}).ok,false);
assert.equal(e.automaticPromotion,false);assert.equal(e.automaticReward,false);assert.equal(e.automaticPower,false);
console.log(JSON.stringify({gate:'CREW_EVIDENCE_RUNTIME',app:'SNAP_POP',pass:true},null,2));
