const assert=require('node:assert/strict');
const adapter=require('../snap-scene-policy-adapter-v1.js');
const p=adapter.policy();
assert.equal(p.schema,'TAKY_APP_SCENE_POLICY_ADAPTER_V1');
assert.equal(p.app_id,'SNAP_POP');
assert.equal(p.max_visible,3);
assert.equal(p.max_speaking,1);
assert.equal(p.asset_generation_allowed,false);
assert.equal(p.unapproved_member_policy,'EXCLUDE');
assert.equal(p.runtime_eligibility_required,true);
assert.equal(p.fallback_scope,'SAME_CHARACTER_APPROVED_ONLY');
assert.equal(adapter.choosesCharacters,false);
assert.equal(adapter.selectsAssets,false);
assert.equal(adapter.generatesArt,false);
const bound=adapter.bind({scene_id:'test'});
assert.equal(bound.scene_policy_id,'SNAP_SCENE_POLICY_V1');
assert.equal(bound.design_gate_required,true);
assert.equal(bound.asset_generation_allowed,false);
console.log(JSON.stringify({gate:'APP_SCENE_POLICY_ADAPTER',app:p.app_id,pass:true},null,2));
