const {test,expect}=require('@playwright/test');
const sizes=[[375,667],[390,844],[430,932],[1024,768]];
for(const [width,height] of sizes){
test('isolated companion onboarding complete path, assets, restore and rename '+width+'x'+height,async({page})=>{
  test.setTimeout(60000);
  await page.setViewportSize({width,height});
  const failures=[];page.on('pageerror',e=>failures.push(e.message));
  await page.goto('http://127.0.0.1:4173/onboarding/');
  await expect(page.locator('#app')).toHaveAttribute('data-step','0');
  await expect(page.locator('.welcome-cta')).toBeVisible();
  expect(await page.evaluate(()=>!!globalThis.CompanionCrewState)).toBe(true);
  await page.locator('.welcome-cta').click();
  await expect(page.locator('.approved-stage>img')).toHaveAttribute('src','ui/approved/first_meeting_selection_source.png');
  expect(await page.locator('.approved-stage>img').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
  await page.locator('button.approved-tap.cta').click();
  await expect(page.locator('#app')).toHaveAttribute('data-step','2');
  await expect(page.locator('.approved-stage')).toHaveAttribute('data-selection-phase','crew');
  const first=JSON.parse(await page.evaluate(()=>localStorage.getItem('expedition_ui_draft')));
  expect(Object.values(first.crewLedger.members).every(x=>!!x.firstMetAt)).toBe(true);
  for(let i=0;i<5;i++)await page.locator('button.approved-tap.portrait').nth(i).click();
  await expect(page.locator('.approved-count')).toHaveText('5/6');
  await page.screenshot({path:'onboarding/render-evidence/crew-'+width+'x'+height+'.png'});
  await page.locator('button.approved-tap.cta').click();
  await expect(page.locator('.approved-stage')).toHaveAttribute('data-selection-phase','primary');
  await expect(page.locator('button.approved-tap.cta')).toBeDisabled();
  await page.locator('button.approved-tap.portrait').nth(1).click();
  await expect(page.locator('.approved-primary-guide')).toContainText('로리');
  await page.locator('button.approved-tap.cta').click();
  await expect(page.locator('#app')).toHaveAttribute('data-step','3');
  await page.reload();
  await expect(page.locator('#app')).toHaveAttribute('data-step','3');
  const reloaded=JSON.parse(await page.evaluate(()=>localStorage.getItem('expedition_ui_draft')));
  expect(reloaded.primaryCompanionId).toBe('lori');
  await page.locator('.mobile-profile input.field').fill('테스트아이');
  await page.locator('#profileNext').click();
  await expect(page.locator('#app')).toHaveAttribute('data-step','4');
  await page.locator('.object[data-item="map"]').click();
  await page.locator('#bag').click();
  await page.locator('.mobile-packing .mobile-cta').click();
  await expect(page.locator('#app')).toHaveAttribute('data-step','5');
  await page.locator('.world-option').first().click();
  await expect(page.locator('#app')).toHaveAttribute('data-step','6');
  await page.locator('.world-cta').click();
  await page.locator('#islandName').fill('테스트섬');
  await page.locator('#islandNext').click();
  await expect(page.locator('#app')).toHaveAttribute('data-step','8');
  await page.locator('.world-cta').click();
  await page.locator('#campName').fill('테스트캠프');
  await page.locator('#campNext').click();
  await expect(page.locator('#app')).toHaveAttribute('data-step','10');
  await page.locator('.home-navigation button').filter({hasText:'탐험대'}).click();
  await expect(page.locator('.crew-primary')).toContainText('로리');
  const lori=page.locator('.crewlist>div').nth(1);
  await lori.getByRole('button',{name:'이름 바꾸기'}).click();
  await page.locator('#rename-lori').fill('별로리');
  await page.locator('.crewlist>div').nth(1).getByRole('button',{name:'저장'}).click();
  await expect(page.locator('.crew-primary')).toContainText('별로리');
  await page.screenshot({path:'onboarding/render-evidence/home-'+width+'x'+height+'.png'});
  await page.reload();
  await expect(page.locator('#app')).toHaveAttribute('data-step','10');
  const persisted=JSON.parse(await page.evaluate(()=>localStorage.getItem('expedition_ui_draft')));
  expect(persisted.crewLedger.members.lori.id).toBe('lori');
  expect(persisted.crewLedger.members.lori.firstName).toBe('로리');
  expect(persisted.crewLedger.members.lori.currentName).toBe('별로리');
  expect(persisted.crewLedger.members.lori.nameHistory).toHaveLength(1);
  expect(persisted.crewLedger.primaryHistory).toHaveLength(1);
  expect(failures).toEqual([]);
  expect(page.url()).toContain('/onboarding/');
});
}
